<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Character extends Model
{
    const PROPERTIES = [
        'event'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::deleted(function ($character) {
            foreach ($character->events as $event) {
                Event::forgetCache($event->id);
            }
        });

        self::updated(function ($character) {
            foreach ($character->events as $event) {
                Event::forgetCache($event->id);
            }
        });
    }

    public function events()
    {
        return $this->morphedByMany('App\Models\Event', 'property', 'character_property');
    }

    public function properties()
    {
        return $this->hasMany('App\Models\CharacterProperty', 'character_id');
    }


    public function types()
    {
        return $this->belongsToMany('App\Models\CharacterType', 'character_type', 'character_id', 'type_id');
    }

    public function character()
    {
        return $this->morphTo('character');
    }

    public function getCharacterTypeFaAttribute()
    {
        if ($this->character_type == 'celebrity') {
            return 'مشاهیر';
        }
    }
}
