<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redis;
use Laravel\Scout\Searchable;

class Place extends Model
{
    use SoftDeletes, Searchable;

    const CacheItemPeriod = 10;
    const CachePagePeriod = 5;
    const CacheVisitsPeriod = 60;
    const CacheRatingPeriod = 20;
    const DetailTypes = [
        'address' => 'آدرس',
        'tell' => 'شماره تلفن',
        'schedule' => 'ساعت کاری',
        'custom_link' => '',
        'service_provider' => 'ارائه دهنده خدمت'
    ];
    protected $guarded = [];
    protected $casts = [
        'media' => 'array',
        'links' => 'array',
        'meta' => 'array',
        'details' => 'array'
    ];

    public static function getById($id)
    {
        $place = self::with(['city', 'language', 'type', 'authors', 'photographers', 'tags', 'cities', 'cities.city'])
            ->findOrFail($id);


        return $place;
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        self::created(function ($place) {
            \App\Models\Searchable::create([
                'searchable_type' => 'place',
                'searchable_id' => $place->id
            ]);
            Artisan::call('images:removehttp');
        });

        self::updated(function ($place) {
            if (!app()->runningInConsole()) {
                Artisan::call('images:removehttp');
                Category::indexRelatedCategoriesTo($place);
            }
            foreach ($place->events as $event) {
                Event::forgetCache($event->id);
            }
            Post::flushPostsIndex();
        });

        self::deleted(function ($place) {
            $place->searchables()->delete();
            $place->comments()->delete();
            $place->bookmarks()->delete();
            $place->ratings()->delete();
            $place->tags()->delete();
            if ($place->events()->exists()) {
                foreach ($place->events as $event) {
                    $event->update([
                        'place_id' => null
                    ]);
                }
            }

            foreach ($place->posts as $post) {
                $post->delete();
            }
            Post::flushPostsIndex();
        });
    }

    public static function flushPagesCache()
    {

    }

    public static function storeVisits()
    {
        $place_keys = Redis::keys(config('cache.prefix') . 'laravel:Place:*:TemporaryVisits');

        foreach ($place_keys as $key) {
            $visits = Redis::smembers($key);
            $place_id = explode(':', $key)[2];

            foreach ($visits as $visit) {
                $user_id = explode(':', $visit)[1];

                if (!$user_id || strlen($user_id) < 1) {
                    $user_id = null;
                }

                Visit::create([
                    'visitable_type' => 'place',
                    'visitable_id' => $place_id,
                    'user_id' => $user_id
                ]);
            }

            Redis::del($key);
        }
    }

    public static function deleteDailyVisitsCache()
    {
        $keys = Redis::keys(config('cache.prefix') . 'laravel:Place:*:DailyVisits');
        foreach ($keys as $key) {
            Redis::del($key);
        }
    }

    public function toSearchableArray()
    {
        $array = [
            'id' => $this->id,
            'name' => $this->name
        ];

        return $array;
    }

    public function incrementVisits(Request $request)
    {
        $result = Redis::sadd(config('cache.prefix') . 'laravel:Place:' . $this->id . ':TemporaryVisits', 'user_id:' . Auth::id());

        $this->cacheDailyVisitsIfNotCached();

        if ($result > 0) {
            Redis::hincrby(config('cache.prefix') . 'laravel:Place:' . $this->id . ':DailyVisits', date('Y-m-d'), 1);
        }
    }

    private function cacheDailyVisitsIfNotCached()
    {
        if (!Redis::exists(config('cache.prefix') . 'laravel:Place:' . $this->id . ':DailyVisits'))
            $this->cacheDailyVisits();
    }

    private function cacheDailyVisits()
    {
        $visits = Visit::where('visitable_id', '=', $this->id)
            ->where('visitable_type', '=', 'place')
            ->selectRaw('COUNT(*) as count, CAST(created_at AS DATE) as date')
            ->groupBy(DB::raw('CAST(created_at as DATE)'))
            ->get();

        foreach ($visits as $visit) {
            Redis::hset(config('cache.prefix') . 'laravel:Place:' . $this->id . ':DailyVisits', $visit->date, $visit->count);
        }
    }

    public function getVisitsFromCache()
    {
        $this->cacheDailyVisitsIfNotCached();
        return Redis::hgetall(config('cache.prefix') . 'laravel:Place:' . $this->id . ':DailyVisits');
    }

    public function getVisitsCountFromCache()
    {
        $this->cacheDailyVisitsIfNotCached();

        $values = Redis::hvals('laravel:Place:' . $this->id . ':DailyVisits');
        $count = 0;

        foreach ($values as $value)
            $count += $value;

        return $count;
    }

    public function events()
    {
        return $this->hasMany('App\Models\Event');
    }

    public function visits()
    {
        return $this->morphMany('App\Models\Visit', 'visitable');
    }

    public function getRatingFromCache()
    {
        $avg = $this->ratings()->avg('rate') ?: 0;
        return $avg;
    }

    public function ratings()
    {
        return $this->morphMany('App\Models\Rating', 'ratable');
    }

    public function posts()
    {
        return $this->morphMany('App\Models\Post', 'postable');
    }

    public function getCities()
    {
        return $this->cities()->get()->pluck('city');
    }

    public function cities()
    {
        return $this->morphMany('App\Models\Citiable', 'citiable');
    }

    public function searchables()
    {
        return $this->morphMany('App\Models\Searchable', 'searchable');
    }

    public function comments()
    {
        return $this->morphMany('App\Models\Comment', 'commentable');
    }

    public function images()
    {
        return $this->morphMany('App\Models\Imagable', 'imagable');
    }

    public function bookmarks()
    {
        return $this->morphMany('App\Models\Bookmark', 'bookmarkable');
    }

    public function tags()
    {
        return $this->morphToMany('App\Models\Tag', 'tagable');
    }

    public function photographers()
    {
        return $this->morphToMany('App\Models\Photographer', 'photographerable');
    }

    public function authors()
    {
        return $this->morphToMany('App\Models\Author', 'authorable');
    }

    public function city()
    {
        return $this->belongsTo('App\Models\City');
    }

    public function admin()
    {
        return $this->belongsTo('App\Models\Admin');
    }

    public function language()
    {
        return $this->belongsTo('App\Models\Language');
    }

    public function type()
    {
        return $this->belongsTo('App\Models\PlaceType');
    }

    public function scopeLanguage($query, $langauge_id)
    {
        return $query->where('language_id', $langauge_id);
    }
}
